### ISSUE TITLE
Use zeitwerk for auto-loading

### ISSUE THREAD

**Issue by skatkov** [cheddar-me/pecorino#10]
I'd like to suggest taking it even further and use `zeitwerk`. We have so many rails dependencies for this gem, that it's safe to assume, that `zeitwek` will be available in most environments where this gem is installed.

Zeitwerk offers some significant improvements, besides lazy-loading, there is a good summary of those [here](https://discourse.dry-rb.org/t/what-are-the-differences-between-the-default-loader-and-the-zeitwerk-loader/1462/2). It seems like a worthy change.

**Comment by julik** [comment]
What benefits do end-users get from using Zeitwerk inside a library?

**Comment by skatkov** [comment]
@julik no need to write any requires and avoid all issues related with that.

Plus original autoloader is [discouraged for usage](https://bugs.ruby-lang.org/issues/5653) and a lot of [those issues](https://discourse.dry-rb.org/t/what-are-the-differences-between-the-default-loader-and-the-zeitwerk-loader/1462/2) seem to be resolved by zeitwerk.

**Comment by julik** [comment]
While I do understand the benefit of autoloading (but most of all: _reloading_) for parts of actual _apps_ (the end consumers of a library such as Pecorino) I don't see the point of using a third-party autoloader in a library still. The ticket that you listed does not specify autoloading getting removed from the language or from MRI, it just lists a long discussion why it is not optimal - but there was hardly any conclusion.

As far as libraries go, I believe there are a few things to keep in mind over others:

* Do not force too many dependencies onto the end user. I myself have worked on apps where ActiveRecord was used, yet the rest of Rails (including autoloaders) did not. I would not expect a library to enforce an "umbrella" dependency on me unless it was absolutely instrumental. Skipping loading 2 source files is not, by any means, absolutely instrumental
* Introduce less "complications" for when the end user needs to read the source code of the library to debug an issue of some kind. For example: how high is the cost of force-loading all adapters (we will have 3 at most) always, versus having the user understand that _some kind_ of autoloading is used, or - even further - having to understand the workings of Zeitwerk to debug something the library does in their app? If the cost is low, we better use the stupidest, most standard "something" and not try to be clever
* Do not make folks' apps slow to boot. This is where autoloading is useful - but how much impact does force-loading 3 source files cause? For example, if we were talking about a sizable binary dependency (like gRPC or other heavyweight lib) - it would be a good idea not to load it unless strictly necessary. But is loading 3 source files such an issue?

Based on the above: no, we should not impose zeitwerk from a library, we might not even need to do autoloading at all, and I do not believe using zeitwerk here adds value for end-users. It should be on the app consuming the library to decide whether they want to use Zeitwert, standard autoload or just a vanilla `require`.
